---
language: python
services: docker

env:
  global:
    - ROLE_NAME: aws-ecr-credential-helper
  matrix:
    - MOLECULE_DISTRO: debian:8
    - MOLECULE_DISTRO: debian:9
    - MOLECULE_DISTRO: debian:10
    - MOLECULE_DISTRO: ubuntu:16.04
    - MOLECULE_DISTRO: ubuntu:18.04
    - MOLECULE_DISTRO: ubuntu:19.04
    - MOLECULE_DISTRO: ubuntu:19.10

install:
  # Install test dependencies.
  - pipenv install

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
